modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="https://github.com/QingMo-A/MCWebUI/issues"

[[mods]]
modId="mcwebui"
version="${file.jarVersion}"
displayName="MCWebUI"
authors="QingMo-A"
description='''Backend-neutral bundled web UI runtime for NeoForge.'''

[[dependencies.mcwebui]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="CLIENT"

[[dependencies.mcwebui]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="CLIENT"

[[dependencies.mcwebui]]
modId="mcef"
type="required"
versionRange="[2.1.6-1.21.1,)"
ordering="AFTER"
side="CLIENT"
